### ISSUE TITLE
the Dockerfile build binary before tests and lint

### ISSUE THREAD

**Issue by prune998** [chris-crone/containerized-go-dev#2]
Maybe I've been doing it wrong all my life, but what's the point of building first, before testing or linting ? 
I usually see linting first, then tests, and if everything is fine (which should produce a working binary), build.

Sorry to ask than in an issue... :)
BTW, great work explaining all these features

**Comment by puneri78** [comment]
yes, this is a valid point. 
To workaround had to add another target to build container image, that gets called post lint and test.

**Comment by chris-crone** [comment]
Sorry for the tardy reply, I was not watching this repo.

A lot of errors can be caught by the compiler so I use that as the first "test". It may depend on what language you are using as to which order you perform the steps. e.g.: For Python, it would make sense to test before packaging as it's a dynamic language.

The guiding rule that I would use is to try to make builds fail as quickly as possible so that the CI gives the quickest possible feedback.
