### ISSUE TITLE
Issue with exporting go test coverage output

### ISSUE THREAD

**Issue by puneri78** [chris-crone/containerized-go-dev#3]
first of all thank you for sharing this system, 
I tried this system but unable to use for unit-test target with exporting test coverage output file for use with CI system.
I did mount the folder --output 

go test -coverprofile=/out/cover.out ./... 

any idea what could be missing here ?

**Comment by chris-crone** [comment]
Hi @puneri78!

In order to get the coverage results out of the image, you will need to change the `go test` command as you show and then create a new stage at the end of the Dockerfile. Something like

```dockerfile
FROM scratch AS test-coverage
COPY --from=unit-test /out/cover.out cover.out
```

You will then be able to run the following and see your `cover.out` in the `coverage/` directory on your host:
```console
$ docker build . --output coverage/ --target test-coverage
```

**Comment by puneri78** [comment]
worked with one workaround though i.e. need to build binary and then test

any idea why this workaround is required ?

go build -o /out/example . && go test -coverprofile=/out/cover.out ./...

> FROM base AS build
> ARG TARGETOS
> ARG TARGETARCH
> RUN --mount=target=. \
>     --mount=type=cache,target=/root/.cache/go-build \
>     GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /out/bin/example .
> 
> FROM base AS unit-test
> RUN --mount=target=. \
>     --mount=type=cache,target=/root/.cache/go-build \
>     go build -o /out/example . && go test -coverprofile=/out/cover.out ./...
> 
>

**Comment by chris-crone** [comment]
Again, sorry for the tardy reply @puneri78!

> any idea why this workaround is required ?

I think it's because `go test` doesn't create the directory for the coverage report while `go build` does. I've put up and merged a PR that adds this functionality: https://github.com/chris-crone/containerized-go-dev/pull/4

Note the `mkdir` in the Dockerfile there.
